version: "3.7"
services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 drf.wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
